### ISSUE TITLE
Missing dependencies from package.json

### ISSUE THREAD

**Issue by domus71** [AnandChowdhary/auto-i18n#299]
Missing dependencies such mkdirp

**Comment by domus71** [comment]
I'm getting this error

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'mkdirp'
Require stack:
- C:\CostisWork\NodeJS\autoTranslate\node_modules\fraud\dist\index.js
- C:\CostisWork\NodeJS\autoTranslate\node_modules\auto-i18n\dist\index.js
- C:\CostisWork\NodeJS\autoTranslate\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\CostisWork\NodeJS\autoTranslate\node_modules\fraud\dist\index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\CostisWork\\NodeJS\\autoTranslate\\node_modules\\fraud\\dist\\index.js',
    'C:\\CostisWork\\NodeJS\\autoTranslate\\node_modules\\auto-i18n\\dist\\index.js',
    'C:\\CostisWork\\NodeJS\\autoTranslate\\index.js'
  ]
}

**Comment by AnandChowdhary** [comment]
This seems like an error with @AnandChowdhary/fraud, so I'll check that.

**Comment by AnandChowdhary** [comment]
Reproduced this as a production install missing runtime deps (`dotenv` first, then `mkdirp` from `fraud`). Opened #387 with a dependency-manifest fix and a production-install smoke check.
